#! /usr/bin/env python3

# A script for getting the smallest prime factor of an integer.
"A module for getting the smallest prime factor of an integer."

import sys

# Define functions after importing modules and before other code

def get_smallest_prime_factor(n):
    """
    Returns the smallest integer that is a factor of `n`.
    If `n` is a prime number `None` is returned.
    Parameters
    ----------
    n : int
        The integer to be factored
    
    Returns
    ----------
    int or None
        The smallest integer that is a factor of `n`
        or None if `n` is a prime number.
    """
    for i in range(2, n):
        if (n % i) == 0:
            return i
